name:                HINT
version:             0.1.0.0
github:              "nicuveo/HINT"
license:             TBD
author:              "Antoine Leblanc"
maintainer:          "nicuveo@gmail.com"
copyright:           "2021 Antoine Leblanc"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/nicuveo/HINT#readme>

dependencies:
 - base >= 4.7 && < 5
 - extra
 - megaparsec
 - monad-loops
 - mtl
 - text
 - vector

default-extensions:
 - BlockArguments
 - FlexibleContexts
 - FlexibleInstances
 - LambdaCase
 - MultiWayIf
 - OverloadedStrings
 - StrictData
 - TupleSections
 - TypeApplications
 - TypeFamilies

library:
  source-dirs: src
  ghc-options:
#    - -Wall
    - -fwarn-tabs
    - -fno-warn-unused-do-bind

tests:
  tests:
    source-dirs:
      - src
      - test
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    ghc-options:
      - -fno-warn-missing-signatures
    main: Tests.hs
