name:                hint
version:             0.1.0.0
github:              "nicuveo/hint"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hint#readme>

dependencies:
 - base >= 4.7 && < 5
 - extra
 - megaparsec
 - monad-loops
 - mtl
 - text
 - vector

default-extensions:
 - BlockArguments
 - FlexibleContexts
 - FlexibleInstances
 - LambdaCase
 - MultiWayIf
 - OverloadedStrings
 - StrictData
 - TupleSections
 - TypeApplications
 - TypeFamilies

library:
  source-dirs: src
  ghc-options:
#    - -Wall
    - -fwarn-tabs
    - -fno-warn-unused-do-bind

tests:
  unit-tests:
    source-dirs:
      - src
      - test
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    ghc-options:
      - -fno-warn-missing-signatures
    main: Tests.hs
