name:                hint
version:             0.1.0.0
github:              "nicuveo/hint"
license:             TBD
author:              "Antoine Leblanc"
maintainer:          "nicuveo@gmail.com"
copyright:           "2023 Antoine Leblanc"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/nicuveo/HINT#readme>

language: GHC2021

ghc-options:
  - -Wcompat
  - -Werror
  - -Weverything
  # everything includes a bit too much: disable unrequired ones
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe
  # turn on additional features
  - -fwarn-tabs
  - -foptimal-applicative-do

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - RankNTypes
  - RecordWildCards
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base
  - Earley
  - containers
  - extra
  - hashable
  - lens
  - megaparsec
  - monad-validate
  - mtl
  - parser-combinators
  - re2
  - scientific
  - text
  - transformers
  - transformers-base
  - unordered-containers

library:
  source-dirs: src
  other-modules:
    - Prelude

executables:
  evalexpr:
    main: Main.hs
    source-dirs: [src, app]
    dependencies:
      - directory
      - filepath
      - haskeline
      - monad-loops
      - pretty-simple

tests:
  tests:
    source-dirs: [src, test]
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    ghc-options:
      - -fno-warn-missing-signatures
    main: Tests.hs
